// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR_Vuejs__Demo.Models;

namespace SignalR_Vuejs__Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200121045259_add_windows_column")]
    partial class add_windows_column
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignalR_Vuejs__Demo.Models.PredZapBD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DATE");

                    b.Property<string>("EDIT");

                    b.Property<string>("FIO");

                    b.Property<string>("LEADING");

                    b.Property<string>("TIME");

                    b.Property<string>("WINDOW");

                    b.HasKey("Id");

                    b.ToTable("PredZapBD");
                });
#pragma warning restore 612, 618
        }
    }
}
